name: build-and-deploy

on:
  push:
    branches: [ main ]
    paths:
      - "Dockerfile"
      - "package*.json"
      - "next.config.ts"
      - "app/**"
      - "public/**"
      - "libs/**"
      - "types/**"
      - "prisma/**"
      - "k8s/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Change to lowercase
        run: |
          echo "IMAGE_LC=${IMAGE,,}" >>${GITHUB_ENV}

      - name: 빌드 앤 푸시
        uses: docker/build-push-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & push image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_BASE_URL=/api \
            -t "$IMAGE_LC" .
          docker push "$IMAGE_LC"

      - name: Load kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Render manifests with image tag
        run: |
          sed -i "s#ghcr.io/front-end-bootcamp-plus-5/ssemtle:IMAGE_TAG#${IMAGE_LC}#g" k8s/deployment.yaml

      - name: Apply manifests & wait for rollout
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl -n apps rollout status deploy/ssemtle --timeout=180s
